### ISSUE TITLE
Hydrographs differ when running a small part of a larger model

### ISSUE THREAD

**Issue by BernardoTeufel** [CSHS-CWRA/RavenHydroFramework#20]
### Setup Information

- Raven version: 3.6
- Operating System: Ubuntu 20.04

### Description

Ran two similar routing-only Raven simulations forced by gridded runoff. One for the entire Mackenzie basin, and the second upstream of the outlet of Great Bear Lake.

There are three gauges in the shared domain. For the gauge without any lakes in the upstream area (sub2024874), the results look almost as expected (no difference whatsoever between both hydrographs), except for the last timestep:

![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/a4b7ad84-bbf5-4b1b-8e70-a85043116d1f)

For the other two gauges (which have upstream lakes), simulations differ significantly:

![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/be8e2303-600e-4936-a9d7-6b752dcff06e)
![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/3a2933b3-1ebc-4545-b007-32f0736eb360)

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by analytophile** [comment]
Hi Bernardo - can you generate and check the ForcingFunctions.csv file to ensure these are identical, then also examine the differences between ReservoirStages.csv and ReservoirMassBalance.csv files so we can pinpoint the source of the deviation. Its hard with a Mackenzie-sized model to nail this down to the actual problem.

**Comment by analytophile** [comment]
I believe this was fixed in revision fb00c23 - it was an issue that was arising when land use parameter LAKE_PET_CORR was not specified in the .rvp file.  Could you specify this parameter as 1.0 in v3.7 with a PET method other than PET_NONE and verify whether the issue is reconciled?

**Comment by BernardoTeufel** [comment]
I've used the latest version from this repository, and I've set `LAKE_PET_CORR` to 1.0 in the .rvp file for both simulations. I did not specify any PET method, which defaults to `PET_HARGREAVES_1985`.

The issue still occurs. I looked into `ReservoirMassBalance.csv` and confirmed that the issue is (still) related to evaporation (black line is Great Bear simulation, red line is entire Mackenzie, for the same reservoir in both simulations):

![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/1f61db6b-3b39-489e-b42c-187a38e252fb)

I looked into the `PET_HARGREAVES_1985` algorithm, which depends only on temperature (F->temp_daily_max, F->temp_daily_min and F->temp_daily_ave) and radiation (F->ET_radia). Radiation is identical for both simulations, but temperature can differ by over 10 degC between both simulations (first 5 days are identical, then differences start to grow):

![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/b2ef32f5-21ab-4bf3-85b4-4d8b1ee40362)

Plot is for difference in F->temp_daily_ave, and plots for max and min look similar.

**Comment by analytophile** [comment]
how are you supplying temperature forcings to the model? i.e., is this gage-based or gridded temperature data? I assume that these are temperatures for the reservoir HRU, correct? And that supplied temperature datasets are identical?

**Comment by BernardoTeufel** [comment]
I'm supplying gridded temperature data (hourly data), and both simulations are reading the same file. The temperatures I plotted are indeed for the reservoir HRU.
